// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: darak/control/v1/control.proto

// darak's control plane, as resources.
//
// This is the seam between darak — which decides WHO may do a thing (an admin,
// a team's owner) — and the service that owns the roster's SOURCE: it edits the
// version-controlled roster (a commit, a pull request) when told to. darak is
// the gate; the server behind this contract is the sink that "just does what it
// is told". There is no database here and darak keeps none: the roster stays the
// single source of truth, and this API only asks the thing that owns it to
// change it.
//
// usersync is unchanged and downstream of all of this. A method here starts a
// roster-update pipeline — edit the source, land the change — and usersync then
// reconciles the running system to the new roster, which is what makes an
// account actually appear. So Enrollment.Add BEGINS that pipeline, and an
// enrollment's Stage is where the pipeline has got to.
//
// The shape follows payday (github.com/lesomnus/payday): a resource per concept,
// each with the standard method vocabulary — Add / Get / List / Watch / Erase —
// rather than a verb per operation. A membership is a resource, so joining a
// group is Add and leaving is Erase; an onboarding is a resource, so requesting
// one is Add, asking how far it got is Get, and following it as the pipeline
// advances is Watch.

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stage is where an enrollment stands. It only moves forward, except that a
// FAILED one may be retried into REQUESTED.
type Stage int32

const (
	Stage_STAGE_UNSPECIFIED Stage = 0
	// Recorded; nothing has started (the approval queue, with no automation).
	Stage_STAGE_REQUESTED Stage = 1
	// The account is being created (a change is open against the roster).
	Stage_STAGE_CREATING Stage = 2
	// A person has to decide before it can proceed.
	Stage_STAGE_AWAITING_APPROVAL Stage = 3
	// The account exists and may sign in. account is set.
	Stage_STAGE_READY Stage = 4
	// This identity will not be given an account here.
	Stage_STAGE_DENIED Stage = 5
	// A transient failure; the next attempt may get further.
	Stage_STAGE_FAILED Stage = 6
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_REQUESTED",
		2: "STAGE_CREATING",
		3: "STAGE_AWAITING_APPROVAL",
		4: "STAGE_READY",
		5: "STAGE_DENIED",
		6: "STAGE_FAILED",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED":       0,
		"STAGE_REQUESTED":         1,
		"STAGE_CREATING":          2,
		"STAGE_AWAITING_APPROVAL": 3,
		"STAGE_READY":             4,
		"STAGE_DENIED":            5,
		"STAGE_FAILED":            6,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_darak_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_darak_control_v1_control_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{0}
}

// Role is what a membership grants. It unifies what the roster spells three
// ways: a writing member, a read-only reader group, and an owner (administrator
// of the group).
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_MEMBER      Role = 1 // read and write the group's folder
	Role_ROLE_READER      Role = 2 // read only
	Role_ROLE_OWNER       Role = 3 // may add and remove the group's members
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_MEMBER",
		2: "ROLE_READER",
		3: "ROLE_OWNER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_MEMBER":      1,
		"ROLE_READER":      2,
		"ROLE_OWNER":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_darak_control_v1_control_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_darak_control_v1_control_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{1}
}

// Enrollment is an in-progress onboarding of an identity that signed in through
// SSO and resolves to no account yet. darak Adds one on that first sign-in and
// Gets it afterwards to tell the person how far it has got — turning what used
// to be a fire-and-forget webhook into something a page can track.
type Enrollment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id the client tracks the enrollment by. Assigned by the server on
	// Add; supplied on Get and Erase.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Who the provider said this is. The subject is the durable handle; the
	// addresses are what a rule and a person read.
	Issuer  string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Emails  []string `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	// Display name from the provider, for a person reviewing the request.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Where the request stands right now. This is what the interface renders as
	// live progress instead of one static "waiting for approval" line.
	Stage Stage `protobuf:"varint,6,opt,name=stage,proto3,enum=darak.control.v1.Stage" json:"stage,omitempty"`
	// The account, once one exists. Empty until stage is READY.
	Account string `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	// A human-readable line for the pending person, from the server. Optional;
	// darak supplies a default per stage when it is empty.
	Message string `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	// When this enrollment last changed. It is the version a Watch orders by: a
	// watch sends state, and two updates about one enrollment can arrive out of
	// order, so a client keeps the newer and drops an older one it holds already.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enrollment) Reset() {
	*x = Enrollment{}
	mi := &file_darak_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enrollment) ProtoMessage() {}

func (x *Enrollment) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enrollment.ProtoReflect.Descriptor instead.
func (*Enrollment) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Enrollment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enrollment) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Enrollment) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Enrollment) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Enrollment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enrollment) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *Enrollment) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Enrollment) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Enrollment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddEnrollmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account name to create. darak derives it from the primary address's
	// local part (`dohyun.jang@company.com` → `dohyun.jang`) — the same rule
	// trust-email matches an EXISTING member by, so the account this creates signs
	// in cleanly the next time. It is passed, not re-derived here: darak owns the
	// rule for what an address names, and the server is told the answer.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Who the provider said this is, recorded so the account binds to this subject
	// when it appears.
	Issuer  string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Emails  []string `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	// Display name from the provider, for a person reviewing the request.
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEnrollmentRequest) Reset() {
	*x = AddEnrollmentRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEnrollmentRequest) ProtoMessage() {}

func (x *AddEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*AddEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *AddEnrollmentRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddEnrollmentRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AddEnrollmentRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AddEnrollmentRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *AddEnrollmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentRequest) Reset() {
	*x = GetEnrollmentRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentRequest) ProtoMessage() {}

func (x *GetEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnrollmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEnrollmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only enrollments in this stage, if set. The common read is "what is
	// awaiting approval".
	Stage         Stage  `protobuf:"varint,1,opt,name=stage,proto3,enum=darak.control.v1.Stage" json:"stage,omitempty"`
	Size          int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Page          string `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"` // opaque cursor; empty for the first page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsRequest) Reset() {
	*x = ListEnrollmentsRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsRequest) ProtoMessage() {}

func (x *ListEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListEnrollmentsRequest) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *ListEnrollmentsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListEnrollmentsRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type ListEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*Enrollment          `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	NextPage      string                 `protobuf:"bytes,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"` // empty when there is no more
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsResponse) Reset() {
	*x = ListEnrollmentsResponse{}
	mi := &file_darak_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsResponse) ProtoMessage() {}

func (x *ListEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ListEnrollmentsResponse) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *ListEnrollmentsResponse) GetNextPage() string {
	if x != nil {
		return x.NextPage
	}
	return ""
}

type EraseEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseEnrollmentRequest) Reset() {
	*x = EraseEnrollmentRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseEnrollmentRequest) ProtoMessage() {}

func (x *EraseEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EraseEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *EraseEnrollmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WatchEnrollmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Watch one enrollment by id — a pending person following their own onboarding
	// as the pipeline advances — or every enrollment in a stage (AWAITING_APPROVAL
	// for the operator's live queue). Setting neither watches them all.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stage         Stage  `protobuf:"varint,2,opt,name=stage,proto3,enum=darak.control.v1.Stage" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEnrollmentsRequest) Reset() {
	*x = WatchEnrollmentsRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEnrollmentsRequest) ProtoMessage() {}

func (x *WatchEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*WatchEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *WatchEnrollmentsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchEnrollmentsRequest) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

// Membership is an account's place in a group, as a resource. Adding one is
// joining; erasing one is leaving. The role says what the place is worth.
type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=darak.control.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_darak_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *Membership) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Membership) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Membership) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type AddMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=darak.control.v1.Role" json:"role,omitempty"` // defaults to ROLE_MEMBER when unspecified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembershipRequest) Reset() {
	*x = AddMembershipRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembershipRequest) ProtoMessage() {}

func (x *AddMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembershipRequest.ProtoReflect.Descriptor instead.
func (*AddMembershipRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *AddMembershipRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AddMembershipRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AddMembershipRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type EraseMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseMembershipRequest) Reset() {
	*x = EraseMembershipRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseMembershipRequest) ProtoMessage() {}

func (x *EraseMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseMembershipRequest.ProtoReflect.Descriptor instead.
func (*EraseMembershipRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *EraseMembershipRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EraseMembershipRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GradeMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=darak.control.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeMembershipRequest) Reset() {
	*x = GradeMembershipRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeMembershipRequest) ProtoMessage() {}

func (x *GradeMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeMembershipRequest.ProtoReflect.Descriptor instead.
func (*GradeMembershipRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *GradeMembershipRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GradeMembershipRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GradeMembershipRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type ListMembershipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsRequest) Reset() {
	*x = ListMembershipsRequest{}
	mi := &file_darak_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsRequest) ProtoMessage() {}

func (x *ListMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembershipsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memberships   []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsResponse) Reset() {
	*x = ListMembershipsResponse{}
	mi := &file_darak_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsResponse) ProtoMessage() {}

func (x *ListMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_darak_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_darak_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembershipsResponse) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

var File_darak_control_v1_control_proto protoreflect.FileDescriptor

const file_darak_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1edarak/control/v1/control.proto\x12\x10darak.control.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\n" +
	"Enrollment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12-\n" +
	"\x05stage\x18\x06 \x01(\x0e2\x17.darak.control.v1.StageR\x05stage\x12\x18\n" +
	"\aaccount\x18\a \x01(\tR\aaccount\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x01\n" +
	"\x14AddEnrollmentRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"&\n" +
	"\x14GetEnrollmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x16ListEnrollmentsRequest\x12-\n" +
	"\x05stage\x18\x01 \x01(\x0e2\x17.darak.control.v1.StageR\x05stage\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x03 \x01(\tR\x04page\"v\n" +
	"\x17ListEnrollmentsResponse\x12>\n" +
	"\venrollments\x18\x01 \x03(\v2\x1c.darak.control.v1.EnrollmentR\venrollments\x12\x1b\n" +
	"\tnext_page\x18\x02 \x01(\tR\bnextPage\"(\n" +
	"\x16EraseEnrollmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x17WatchEnrollmentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x17.darak.control.v1.StageR\x05stage\"h\n" +
	"\n" +
	"Membership\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.darak.control.v1.RoleR\x04role\"r\n" +
	"\x14AddMembershipRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.darak.control.v1.RoleR\x04role\"H\n" +
	"\x16EraseMembershipRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"t\n" +
	"\x16GradeMembershipRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.darak.control.v1.RoleR\x04role\".\n" +
	"\x16ListMembershipsRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"Y\n" +
	"\x17ListMembershipsResponse\x12>\n" +
	"\vmemberships\x18\x01 \x03(\v2\x1c.darak.control.v1.MembershipR\vmemberships*\x99\x01\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTAGE_REQUESTED\x10\x01\x12\x12\n" +
	"\x0eSTAGE_CREATING\x10\x02\x12\x1b\n" +
	"\x17STAGE_AWAITING_APPROVAL\x10\x03\x12\x0f\n" +
	"\vSTAGE_READY\x10\x04\x12\x10\n" +
	"\fSTAGE_DENIED\x10\x05\x12\x10\n" +
	"\fSTAGE_FAILED\x10\x06*N\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x01\x12\x0f\n" +
	"\vROLE_READER\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x032\xa9\x03\n" +
	"\x11EnrollmentService\x12K\n" +
	"\x03Add\x12&.darak.control.v1.AddEnrollmentRequest\x1a\x1c.darak.control.v1.Enrollment\x12K\n" +
	"\x03Get\x12&.darak.control.v1.GetEnrollmentRequest\x1a\x1c.darak.control.v1.Enrollment\x12[\n" +
	"\x04List\x12(.darak.control.v1.ListEnrollmentsRequest\x1a).darak.control.v1.ListEnrollmentsResponse\x12R\n" +
	"\x05Watch\x12).darak.control.v1.WatchEnrollmentsRequest\x1a\x1c.darak.control.v1.Enrollment0\x01\x12I\n" +
	"\x05Erase\x12(.darak.control.v1.EraseEnrollmentRequest\x1a\x16.google.protobuf.Empty2\xd9\x02\n" +
	"\x11MembershipService\x12K\n" +
	"\x03Add\x12&.darak.control.v1.AddMembershipRequest\x1a\x1c.darak.control.v1.Membership\x12I\n" +
	"\x05Erase\x12(.darak.control.v1.EraseMembershipRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x04List\x12(.darak.control.v1.ListMembershipsRequest\x1a).darak.control.v1.ListMembershipsResponse\x12O\n" +
	"\x05Grade\x12(.darak.control.v1.GradeMembershipRequest\x1a\x1c.darak.control.v1.MembershipB7Z5github.com/lesomnus/darak/control/controlpb;controlpbb\x06proto3"

var (
	file_darak_control_v1_control_proto_rawDescOnce sync.Once
	file_darak_control_v1_control_proto_rawDescData []byte
)

func file_darak_control_v1_control_proto_rawDescGZIP() []byte {
	file_darak_control_v1_control_proto_rawDescOnce.Do(func() {
		file_darak_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_darak_control_v1_control_proto_rawDesc), len(file_darak_control_v1_control_proto_rawDesc)))
	})
	return file_darak_control_v1_control_proto_rawDescData
}

var file_darak_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_darak_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_darak_control_v1_control_proto_goTypes = []any{
	(Stage)(0),                      // 0: darak.control.v1.Stage
	(Role)(0),                       // 1: darak.control.v1.Role
	(*Enrollment)(nil),              // 2: darak.control.v1.Enrollment
	(*AddEnrollmentRequest)(nil),    // 3: darak.control.v1.AddEnrollmentRequest
	(*GetEnrollmentRequest)(nil),    // 4: darak.control.v1.GetEnrollmentRequest
	(*ListEnrollmentsRequest)(nil),  // 5: darak.control.v1.ListEnrollmentsRequest
	(*ListEnrollmentsResponse)(nil), // 6: darak.control.v1.ListEnrollmentsResponse
	(*EraseEnrollmentRequest)(nil),  // 7: darak.control.v1.EraseEnrollmentRequest
	(*WatchEnrollmentsRequest)(nil), // 8: darak.control.v1.WatchEnrollmentsRequest
	(*Membership)(nil),              // 9: darak.control.v1.Membership
	(*AddMembershipRequest)(nil),    // 10: darak.control.v1.AddMembershipRequest
	(*EraseMembershipRequest)(nil),  // 11: darak.control.v1.EraseMembershipRequest
	(*GradeMembershipRequest)(nil),  // 12: darak.control.v1.GradeMembershipRequest
	(*ListMembershipsRequest)(nil),  // 13: darak.control.v1.ListMembershipsRequest
	(*ListMembershipsResponse)(nil), // 14: darak.control.v1.ListMembershipsResponse
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_darak_control_v1_control_proto_depIdxs = []int32{
	0,  // 0: darak.control.v1.Enrollment.stage:type_name -> darak.control.v1.Stage
	15, // 1: darak.control.v1.Enrollment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: darak.control.v1.ListEnrollmentsRequest.stage:type_name -> darak.control.v1.Stage
	2,  // 3: darak.control.v1.ListEnrollmentsResponse.enrollments:type_name -> darak.control.v1.Enrollment
	0,  // 4: darak.control.v1.WatchEnrollmentsRequest.stage:type_name -> darak.control.v1.Stage
	1,  // 5: darak.control.v1.Membership.role:type_name -> darak.control.v1.Role
	1,  // 6: darak.control.v1.AddMembershipRequest.role:type_name -> darak.control.v1.Role
	1,  // 7: darak.control.v1.GradeMembershipRequest.role:type_name -> darak.control.v1.Role
	9,  // 8: darak.control.v1.ListMembershipsResponse.memberships:type_name -> darak.control.v1.Membership
	3,  // 9: darak.control.v1.EnrollmentService.Add:input_type -> darak.control.v1.AddEnrollmentRequest
	4,  // 10: darak.control.v1.EnrollmentService.Get:input_type -> darak.control.v1.GetEnrollmentRequest
	5,  // 11: darak.control.v1.EnrollmentService.List:input_type -> darak.control.v1.ListEnrollmentsRequest
	8,  // 12: darak.control.v1.EnrollmentService.Watch:input_type -> darak.control.v1.WatchEnrollmentsRequest
	7,  // 13: darak.control.v1.EnrollmentService.Erase:input_type -> darak.control.v1.EraseEnrollmentRequest
	10, // 14: darak.control.v1.MembershipService.Add:input_type -> darak.control.v1.AddMembershipRequest
	11, // 15: darak.control.v1.MembershipService.Erase:input_type -> darak.control.v1.EraseMembershipRequest
	13, // 16: darak.control.v1.MembershipService.List:input_type -> darak.control.v1.ListMembershipsRequest
	12, // 17: darak.control.v1.MembershipService.Grade:input_type -> darak.control.v1.GradeMembershipRequest
	2,  // 18: darak.control.v1.EnrollmentService.Add:output_type -> darak.control.v1.Enrollment
	2,  // 19: darak.control.v1.EnrollmentService.Get:output_type -> darak.control.v1.Enrollment
	6,  // 20: darak.control.v1.EnrollmentService.List:output_type -> darak.control.v1.ListEnrollmentsResponse
	2,  // 21: darak.control.v1.EnrollmentService.Watch:output_type -> darak.control.v1.Enrollment
	16, // 22: darak.control.v1.EnrollmentService.Erase:output_type -> google.protobuf.Empty
	9,  // 23: darak.control.v1.MembershipService.Add:output_type -> darak.control.v1.Membership
	16, // 24: darak.control.v1.MembershipService.Erase:output_type -> google.protobuf.Empty
	14, // 25: darak.control.v1.MembershipService.List:output_type -> darak.control.v1.ListMembershipsResponse
	9,  // 26: darak.control.v1.MembershipService.Grade:output_type -> darak.control.v1.Membership
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_darak_control_v1_control_proto_init() }
func file_darak_control_v1_control_proto_init() {
	if File_darak_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_darak_control_v1_control_proto_rawDesc), len(file_darak_control_v1_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_darak_control_v1_control_proto_goTypes,
		DependencyIndexes: file_darak_control_v1_control_proto_depIdxs,
		EnumInfos:         file_darak_control_v1_control_proto_enumTypes,
		MessageInfos:      file_darak_control_v1_control_proto_msgTypes,
	}.Build()
	File_darak_control_v1_control_proto = out.File
	file_darak_control_v1_control_proto_goTypes = nil
	file_darak_control_v1_control_proto_depIdxs = nil
}
