/**
 * Regenerates internal/fuzzy/testdata/vectors.json.
 *
 *   cd web && node scripts/gen-fuzzy-vectors.ts
 *
 * The file is the CONTRACT between the two implementations of this matcher --
 * web/src/lib/fuzzy.ts and internal/fuzzy -- and both test suites read it. It
 * is generated from the TypeScript side because that is the one people have
 * been using since before there was a search route; the Go side has to agree
 * with what already ships, not the other way round.
 *
 * Regenerating it is therefore not a way to make a failing Go test pass. If the
 * two disagree, one of them is wrong, and which one is a question the diff
 * answers.
 */
import { writeFileSync } from 'node:fs'
import { scoreName } from '../src/lib/fuzzy.ts'

// Chosen for what each one pins, not for coverage of the alphabet.
const NAMES = [
  '회의록 2026-08-07.md',
  '발표자료.pdf',
  '예산안.xlsx',
  '데모 영상.mp4',
  '아주 긴 이름을 가진 파일이라 줄임표가 필요한 문서.docx',
  'backup-2026-08.tar.gz',
  'notes.txt',
  'README.md',
  'a-x-ab.txt',
  'file-2.txt',
  'file-10.txt',
  '기획/2026 예산.xlsx',
  // NFD, as a Mac writes it over SMB. Must score the same as the NFC form
  // above, or half a mixed-platform share is unsearchable.
  '회의록 2026-08-07.md'.normalize('NFD'),
  'café.txt'.normalize('NFD'),
  'CAFÉ.txt',
  // Non-BMP: one emoji is two UTF-16 code units, so this pins that positions
  // are counted in code units and not in runes.
  '🎉 파티 계획.txt',
  'ﬁle.txt', // a ligature: folds to itself, length preserved
]

const QUERIES = [
  '',
  'ㅎ',
  'ㅎㅇㄹ',
  'ㅂㅍ',
  'ㅇㅅㅇ',
  'ㅍㅌ',
  '회의',
  '회의'.normalize('NFD'),
  '영상',
  '예산',
  '2026',
  '08-07',
  'nts',
  'notes',
  'BACKUP',
  'readme',
  'ab',
  'file2',
  'café',
  'cafe',
  'CAFÉ'.normalize('NFD'),
  '.txt',
  'zzz',
  '🎉',
]

const cases = []
for (const name of NAMES) {
  for (const query of QUERIES) {
    const m = scoreName(name, query)
    cases.push(
      m === null
        ? { name, query, match: false }
        : { name, query, match: true, score: m.score, pos: m.positions },
    )
  }
}

const out = {
  note:
    'Generated by web/scripts/gen-fuzzy-vectors.ts from web/src/lib/fuzzy.ts. ' +
    'Read by internal/fuzzy/fuzzy_test.go and web/src/lib/fuzzy.test.ts. ' +
    'A disagreement means the two implementations have drifted.',
  cases,
}
const path = new URL('../../internal/fuzzy/testdata/vectors.json', import.meta.url)
writeFileSync(path, JSON.stringify(out, null, 1) + '\n')
console.log(`${cases.length} cases -> ${path.pathname}`)
